/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LOFEOGG1uRv
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { ContentPage } from "@/types";
import React, { FC } from "react";

type ContentPageProp = {
  content: ContentPage;
};

export const AgencyContent: FC<ContentPageProp> = ({ content }) => {
  return (
    <article className="prose prose-gray mx-auto dark:prose-invert min-h-screen">
      <div className="space-y-6">
        <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
          {content.contentPageName}
        </h1>
        <div className="flex items-center gap-2 text-muted-foreground">
          <CalendarIcon className="w-4 h-4" />
          <span>Posted on {content.date_created}</span>
        </div>
      </div>
      <div className="grid gap-8 mt-8">
        <div>
          <img
            src="/placeholder.svg"
            alt="Cover image"
            width={1250}
            height={340}
            className="aspect-video object-cover rounded-md"
          />
          <figcaption className="mt-2 text-sm text-muted-foreground">
            Unleash your creativity with our WYSIWYG editor
          </figcaption>
        </div>
        <div
          className="prose prose-lg px-4"
          dangerouslySetInnerHTML={{ __html: content.pageContent }}
        ></div>
      </div>
    </article>
  );
};

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}
