/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZKvbckRwXT7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Agency } from "@/types";
import Link from "next/link";
import React from "react";

type AgencyList = {
  agencyList: Agency[];
};
export const AgencyList: React.FC<AgencyList> = ({ agencyList }) => {
  return (
    <div className="w-full min-h-screen bg-background">
      <main className="container mx-auto py-12 px-4 md:px-6">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
          {agencyList?.map((agency, index) => {
            return (
              <div
                key={index}
                className="bg-card rounded-lg shadow-lg overflow-hidden"
              >
                <div className="h-48 bg-muted">
                  <img
                    src="/placeholder.svg"
                    alt="Agency Logo"
                    width={400}
                    height={300}
                    className="object-cover w-full h-full"
                    style={{ aspectRatio: "400/300", objectFit: "cover" }}
                  />
                </div>
                <div className="p-6">
                  <h2 className="text-xl font-bold mb-2">
                    {agency.agencyName}
                  </h2>
                  <p className="text-muted-foreground mb-4">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  </p>
                  <Link
                    href={`/agency/${agency.id}`}
                    className="inline-flex items-center justify-center h-10 px-6 rounded-md bg-primary text-primary-foreground font-medium transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};
