/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lbp7xAaTi9D
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";

type NavigationMenu = {
  anchorText: string;
  href: string;
};

const navigation: NavigationMenu[] = [
  { anchorText: "Home", href: "/" },
  { anchorText: "About Us", href: "/about" },
  { anchorText: "Helping Agencies", href: "/agencies" },
  { anchorText: "Resources", href: "/resources" },
  { anchorText: "Directory", href: "/directory" },
];

export function Navbar() {
  return (
    <header className="flex h-16 w-full items-center justify-between bg-background px-4 md:px-6">
      <Link href="#" className="flex items-center gap-2" prefetch={false}>
        <MountainIcon className="h-6 w-6" />
        <span className="text-lg font-semibold">&apos;Ohana First</span>
      </Link>
      <nav className="hidden items-center gap-6 text-sm font-medium md:flex">
        {navigation.map((navLink: NavigationMenu, index) => {
          const { anchorText, href } = navLink;
          return (
            <Link
              key={index}
              href={href}
              className="transition-colors hover:text-primary"
              prefetch={false}
            >
              {anchorText}
            </Link>
          );
        })}
      </nav>
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="outline" size="icon" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="right" className="w-[200px]">
          <div className="grid gap-4 p-4">
            {navigation.map((navLink: NavigationMenu, index) => {
              const { anchorText, href } = navLink;
              return (
                <Link
                  key={index}
                  href={href}
                  className="flex items-center gap-2 text-sm font-medium transition-colors hover:text-primary"
                  prefetch={false}
                >
                  {anchorText}
                </Link>
              );
            })}
          </div>
        </SheetContent>
      </Sheet>
    </header>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
