/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZvYvFMaMa0F
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function OhanaIcon() {
  return (
    <div className="relative flex items-center justify-center w-16 h-16">
      <div className="absolute left-0 top-0 w-4 h-4 rounded-full bg-blue-500">
        <div
          className="absolute top-0 left-0 w-4 h-4 bg-white rounded-full"
          style={{ clipPath: "circle(50% at 75% 50%)" }}
        />
      </div>
      <div className="w-16 h-16 border-4 border-green-500 rounded-full flex items-center justify-center">
        <span className="text-blue-500 font-bold text-lg">HANA</span>
      </div>
    </div>
  );
}
