/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/95vSKd1VM6p
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Resource } from "../types";
import { CONFIG } from "../config/config"
import React from "react";

type ResourcesProp = {
  resources: Resource[];
};

export const ResourceSection: React.FC<ResourcesProp> = async ({
  resources,
}) => {
  return (
    <div className="text-foreground min-h-screen">
      <header className="bg-background text-foreground py-6 md:py-12">
        <div className="container mx-auto px-4 md:px-6">
          <h1 className="text-3xl font-bold md:text-5xl">Resources</h1>
          <p className="mt-2 text-lg md:text-xl">
            Explore our collection of downloads and useful links.
          </p>
        </div>
      </header>
      <main className="container mx-auto py-12 md:py-24 px-4 md:px-6 grid gap-12">
        <section>
          <h2 className="text-2xl font-bold mb-4">Downloads</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {resources.map((resource, index) => {
              if (resource.type === "doc") {
                return (
                  <Link
                    key={index}
                    href={`${CONFIG.ADMIN_URL}/assets/${resource.document}`}
                    className="bg-card p-4 rounded-md shadow hover:bg-accent hover:text-accent-foreground transition-colors"
                    prefetch={false}
                  >
                    <h3 className="text-lg font-medium mb-2">
                      {resource.title}
                    </h3>
                    <p className="text-muted-foreground mb-4">
                      {resource.shortDescription}.
                    </p>
                  </Link>
                );
              }
            })}
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Useful Links</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {resources.map((resource, index) => {
              if (resource.type === "link") {
                return (
                  <Link
                    key={index}
                    href={resource.urlLink}
                    className="bg-card p-4 rounded-md shadow hover:bg-accent hover:text-accent-foreground transition-colors"
                    prefetch={false}
                  >
                    <h3 className="text-lg font-medium mb-2">
                      {resource.title}
                    </h3>
                    <p className="text-muted-foreground mb-4">
                      {resource.shortDescription}
                    </p>
                  </Link>
                );
              }
            })}
          </div>
        </section>
      </main>
    </div>
  );
};
